Merge transform indicator PR (#93)
* New: "Decimal|BooleanTransformIndicator" (#87)

* Create ROCVIndicator.java

ROCVIndicator (Rate of Change of Volume) is like the ROCIndicator, but only for volume (momentum of volume).

* Create ROCVIndicatorTest.java

* Update CHANGELOG.md

* Update PPOIndicator.java

Add optional constructor with default values.

* Update MACDIndicator.java

Add optional constructor with default values.

* Update ROCVIndicator.java

* Update ROCVIndicator.java

* Update ROCIndicator.java

update javadoc.

* Update Strategy.java

- Add convenient methods to combine stategies with "and", "or".
- Add convenient method to get the "opposite" of a strategy.

* Update BaseStrategy.java

Implement methods "and", "or", "opposite".

* Update BaseStrategy.java

* Update Strategy.java

* Update BaseStrategy.java

* Update Strategy.java

* Update BaseStrategy.java

* Update PPOIndicator.java

* Update MACDIndicator.java

* Create DecimalTransformIndicator.java

Transforms any indicator by using common math operations.

* Create BooleanTransformIndicator.java

Transforms any decimal indicator to a boolean indicator by using common logical operators.

* Create DecimalTransformIndicatorTest.java

* Create BooleanTransformIndicatorTest.java

* Update CHANGELOG.md

* Update DecimalTransformIndicator.java

* Update BooleanTransformIndicator.java

* Update DecimalTransformIndicator.java

* Update BooleanTransformIndicator.java

* Update DecimalTransformIndicator.java

* Update BooleanTransformIndicator.java

* Update 'DecimalTransformIndicatorTest' because of failed travis ci build

Reduced precision to 1.3862943611198906:

    java.lang.AssertionError:
    expected:<1.3862943611198905724535279659904> but was:<1.3862943611198906>
    Expected :1.3862943611198905724535279659904
    Actual   :1.3862943611198906