Update 'DecimalTransformIndicatorTest' because of failed travis ci build
Reduced precision to 1.3862943611198906:

    java.lang.AssertionError:
    expected:<1.3862943611198905724535279659904> but was:<1.3862943611198906>
    Expected :1.3862943611198905724535279659904
    Actual   :1.3862943611198906